### ISSUE TITLE
Establecer formato de citación por defecto en normas APA

### ISSUE THREAD

**Issue by RevistasUnivalle** [RevistasUnivalle/ojs#1]
En la vista de **[cualquier artículo](http://revistaingenieria.univalle.edu.co/index.php/ingenieria_y_competitividad/article/view/7651)**, aparece por defecto un formato diferente.
Configurar para que por defecto se muestre el APA.

**Comment by luchoman08** [comment]
En la versión 3.1.1 esta opción existe en la configuración de plugins, en la sección de plugins de citación, formato por defecto.
