### ISSUE TITLE
Revisar la hora del Servidor

### ISSUE THREAD

**Issue by RevistasUnivalle** [RevistasUnivalle/ojs#14]
Cuando se guardan los archivos, quedan con diferente hora, y hasta fecha, del momento en que fueron enviados.
Ejemplo: 
El correo llega con el 30 de Abril
![image](https://user-images.githubusercontent.com/31747871/57234797-0bf14300-6fe7-11e9-9447-3de8ee144ddf.png)
Y el envío en la plataforma qdó con fecha del 1 de Mayo
![image](https://user-images.githubusercontent.com/31747871/57234990-80c47d00-6fe7-11e9-9c5a-378d60c689dc.png)

Enlace del envio:
[http://cuadernosdeadministracion.univalle.edu.co/index.php/cuadernos_de_administracion/workflow/index/7894/1](http://cuadernosdeadministracion.univalle.edu.co/index.php/cuadernos_de_administracion/workflow/index/7894/1)

**Comment by luchoman08** [comment]
Se ha corregido la zona horaria de el php.ini
