### ISSUE TITLE
You don't currently have access to that stage of the workflow.

### ISSUE THREAD

**Issue by RevistasUnivalle** [RevistasUnivalle/ojs#16]
En algunos artículos, el editor de la revista, no puede ingresar al flujo de edición del mismo.
En algunos foros dic q es tema de permisos, sin embargo, cuando reviso los permisos, los del edior general y los del Gestor de la Revista, aparecen bloqueados.

En este momento se está presentando en la revista ingeneiría. 
El usuario **gcontenido** es el editor de la revista.
Cuando entro como el, y voy al articulo "Preferencias Calibration of two mathematical models...", aparece el error _"You can’t have have access to the stage of the workflow"_.

**Comment by luchoman08** [comment]
En el [siguiente foro](https://forum.pkp.sfu.ca/t/you-do-not-currently-have-sufficient-privileges-to-view-the-submission/47420/11) se encuentra información detallada
