### ISSUE TITLE
Error al cargar imagenes

### ISSUE THREAD

**Issue by RevistasUnivalle** [RevistasUnivalle/ojs#2]
En el momento de cargar una imgen o CSS en el [panel de control de las revistas](http://revistas.univalle.edu.co/ojs311/index.php/index/admin/settings), o los "datos del número" en el momento de editar los [issues](http://revistas.univalle.edu.co/ojs311/index.php/pruebas/manageIssues#backIssues), aparece error de permisos, y no se logra completar la operación.

**Comment by luchoman08** [comment]
Error que sucedia en el sitio de pruebas ojs 311, en el sitio de producción actual no sucede
