### ISSUE TITLE
Agregar ítem 'Para autores' a menú de navegación

### ISSUE THREAD

**Issue by jpcv222** [RevistasUnivalle/ojs#4]
Agregar código para mostrar en el menú de navegación de cada revista el ítem 'Para autores'. 
Este ítem deberá redirigir a la url revistas.univalle.edu.co/index.php/NOMBRE_REVISTA/information/authors.

Menú de navegación:
![imagen](https://user-images.githubusercontent.com/42414519/56168221-14ce9600-5fa0-11e9-9370-076a787c469b.png)

**Comment by jpcv222** [comment]
after-311-update

**Comment by luchoman08** [comment]
Las revistas Gastronhub ni para Ambiente no deben tener este item
