### ISSUE TITLE
No se están enviando correos.

### ISSUE THREAD

**Issue by jpcv222** [RevistasUnivalle/ojs#6]
No se están enviando correos a usuarios. Se hizo la prueba con Registro de nuevo usuario; nuevo envío y solicitud de revisión de envío.

**Comment by jpcv222** [comment]
after-311-update

**Comment by luchoman08** [comment]
A la fecha, los correos se están enviando por la función `mail()` de `php`, esta busca algún servidor mail local, `postfix` esta instalado como un simple proxy a gmail. por lo que se debe editar el archivo `/etc/postfix/sasl_passwd/` con una linea con el siguiente formato `[smtp.gmail.com]:587  mail@correounivalle.edu.co:passwd`, posteriormente ejecutar el comando `postmap sassl_passwd` estando en el directorio `/etc/postfix`.
