### ISSUE TITLE
Eliminar la sección Llave API, edición de perfil de usuario. 

### ISSUE THREAD

**Issue by jpcv222** [RevistasUnivalle/ojs#7]
En la versión anterior no salía la sección 'Llave API', la que se requiere no aparezca tampoco en la versión actual. 

Edición de perfil de usuario: 
![imagen](https://user-images.githubusercontent.com/42414519/56171155-de961400-5fa9-11e9-97c5-037da45fade6.png)

**Comment by jpcv222** [comment]
after-311-update

**Comment by luchoman08** [comment]
Se soluciona con la edición de el tema `Univalle` como se muestra en el [siguiente commit ](https://github.com/luchoman08/colombiamedica-theme/commit/6d474b04b919ef7193ce2cdda0d1445708f4a389)
